In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date

           date  product_id  city_id  orders
0    2019-12-10        5628       25       3
1    2018-08-15        3646       14     157
2    2018-10-23        1859       25       1
3    2019-08-17        7292       25       1
4    2019-01-06        4344       25       3
..          ...         ...      ...     ...
995  2018-10-08         255       13       1
996  2018-12-06        5521        7       1
997  2019-05-07         487       26      14
998  2019-03-03        1503       21       2
999  2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [4]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

### Working With Dates

In [6]:
# Converting to datetime datetype

date['date'] = pd.to_datetime(date['date'])

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. Extract year

In [8]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
190 2019-07-13         776       13       2       2019
698 2018-10-03        7567       22       1       2018
500 2019-07-25        5371       22      15       2019
218 2018-08-14        3047        4      24       2018
166 2018-10-11        3946       30       9       2018

### 2. Extract Month

In [10]:
# dt.month -> month number

date['date_month_no'] = date['date'].dt.month

date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
509 2019-07-10        7269       30       2       2019              7
826 2018-09-22         944       28       1       2018              9
70  2019-10-29        6443       16       1       2019             10
754 2019-05-03        2323       25     122       2019              5
673 2019-01-25        6215       22       8       2019              1

In [13]:
# dt.month_name()

date['date_month_name'] = date['date'].dt.month_name()

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
570,2018-12-18,2687,25,31,2018,12,December
990,2018-10-28,3034,0,1,2018,10,October
398,2019-07-19,2307,4,9,2019,7,July
142,2018-08-06,1610,3,1,2018,8,August
768,2018-12-30,4990,1,2,2018,12,December

### 3. Extract Days

In [14]:
# date(2019-05-15) -> dt.day -> 15

date['date_day'] = date['date'].dt.day

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
475,2019-07-25,2898,18,98,2019,7,July,25
503,2018-12-02,25,18,1,2018,12,December,2
397,2019-06-25,6435,13,1,2019,6,June,25
86,2019-06-27,3904,1,29,2019,6,June,27
306,2019-08-01,820,30,2,2019,8,August,1

In [17]:
# day of week
# dt.dayofweek -> gives which day of a week
# monday -> 0  &  sunday -> 6 

date['date_dow'] = date['date'].dt.dayofweek

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
234,2019-04-21,5200,28,19,2019,4,April,21,6
613,2019-04-20,7430,1,2,2019,4,April,20,5
915,2018-10-31,1307,1,3,2018,10,October,31,2
811,2018-11-03,2430,23,8,2018,11,November,3,5
625,2018-10-05,5849,26,5,2018,10,October,5,4

In [18]:
# day of week - name  
# dt.day_name()

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [22]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Saturday','Sunday']),1,0)

date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
497,2018-11-26,2018,11,November,26,0,Monday,0
764,2019-07-26,2019,7,July,26,4,Friday,0
157,2019-02-18,2019,2,February,18,0,Monday,0
866,2019-11-27,2019,11,November,27,2,Wednesday,0
313,2018-12-29,2018,12,December,29,5,Saturday,1

### 4. Extract Week of year

In [32]:
# dt.isocalendar().week -> gives which week of a year is it. (total -> 52/53 weeks a year)

date['date_week_of_year'] = date['date'].dt.isocalendar().week

date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week_of_year
321,2019-12-04,2019,12,December,4,2,Wednesday,0,49
551,2019-06-27,2019,6,June,27,3,Thursday,0,26
10,2019-10-24,2019,10,October,24,3,Thursday,0,43
739,2019-08-06,2019,8,August,6,1,Tuesday,0,32
323,2018-11-19,2018,11,November,19,0,Monday,0,47

### 5. Extract Quarter

In [33]:
# dt.quarter  (4 quarter a year)

date['quarter'] = date['date'].dt.quarter

date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week_of_year,quarter
711,2019-07-13,2019,7,July,13,5,Saturday,1,28,3
487,2019-04-18,2019,4,April,18,3,Thursday,0,16,2
7,2019-03-27,2019,3,March,27,2,Wednesday,0,13,1
197,2018-09-14,2018,9,September,14,4,Friday,0,37,3
828,2019-04-22,2019,4,April,22,0,Monday,0,17,2

### 6. Extract Semester

In [34]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)

date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week_of_year,quarter,semester
358,2019-01-19,2019,1,January,19,5,Saturday,1,3,1,1
690,2018-12-16,2018,12,December,16,6,Sunday,1,50,4,2
500,2019-07-25,2019,7,July,25,3,Thursday,0,30,3,2
785,2019-11-28,2019,11,November,28,3,Thursday,0,48,4,2
539,2019-12-08,2019,12,December,8,6,Sunday,1,49,4,2

### 7. Extract Time elapsed between dates

In [35]:
import datetime as dt

today = dt.datetime.today()

today

datetime.datetime(2026, 3, 1, 19, 54, 54, 224495)

In [36]:
today - date['date']

0     2273 days 19:54:54.224495
1     2755 days 19:54:54.224495
2     2686 days 19:54:54.224495
3     2388 days 19:54:54.224495
4     2611 days 19:54:54.224495
                 ...
995   2701 days 19:54:54.224495
996   2642 days 19:54:54.224495
997   2490 days 19:54:54.224495
998   2555 days 19:54:54.224495
999   2329 days 19:54:54.224495
Name: date, Length: 1000, dtype: timedelta64[ns]

In [37]:
(today - date['date']).dt.days

0      2273
1      2755
2      2686
3      2388
4      2611
       ...
995    2701
996    2642
997    2490
998    2555
999    2329
Name: date, Length: 1000, dtype: int64

In [56]:
# minute passed

np.round((today - date['date']) / np.timedelta64(1,"m"),0)

0      3274315.0
1      3968395.0
2      3869035.0
3      3439915.0
4      3761035.0
         ...
995    3890635.0
996    3805675.0
997    3586795.0
998    3680395.0
999    3354955.0
Name: date, Length: 1000, dtype: float64

In [54]:
# week passed

np.round((today - date['date']) / np.timedelta64(1,"W"),0)

0      325.0
1      394.0
2      384.0
3      341.0
4      373.0
       ...
995    386.0
996    378.0
997    356.0
998    365.0
999    333.0
Name: date, Length: 1000, dtype: float64

### Working With Time

In [43]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [45]:
# Coverting to datetime datatype

time['date'] = pd.to_datetime(time['date'])

In [46]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [48]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.sample(5)

,date,msg,hour,min,sec
511,2013-03-04 23:03:00,парень ищет нормальную девушку для жизни снач...,23,3,0
248,2014-07-02 23:42:00,познакомлюсь с девушкой звоните,23,42,0
296,2013-07-23 23:39:00,Элина хочет просто парня можно с деревни тольк...,23,39,0
301,2014-08-05 01:16:00,. Мне 38. Поцелую женщине 50-55лет. Жду смс фо...,1,16,0
374,2014-02-06 01:33:00,ПРИВЕТ ДЕВОЧКИ!ЕСТЬ ЖЕЛАНИЕ ПООБЩАТЬСЯ ЗВОНИТЕ...,1,33,0

### Extract time part

In [49]:
time['time'] = time['date'].dt.time

time.sample(5)

,date,msg,hour,min,sec,time
712,2014-08-30 22:54:00,М 47/176 для серьёз. отн. с Ж 39-46 ДНЕПР 0...,22,54,0,22:54:00
344,2013-07-27 00:34:00,привет! Блондинка! Глоза голубые. Рост метр се...,0,34,0,00:34:00
872,2014-02-06 00:26:00,если девушки готовые на откровения звоните,0,26,0,00:26:00
426,2013-11-21 02:00:00,Вика 27л ищу своего принца.где ты???????,2,0,0,02:00:00
832,2012-10-11 23:51:00,парень ищет девушку для с.о 0954969918,23,51,0,23:51:00

### Time difference

In [50]:
today - time['date']

0     4459 days 19:04:54.224495
1     4323 days 20:14:54.224495
2     4809 days 19:33:54.224495
3     4111 days 19:23:54.224495
4     4508 days 20:43:54.224495
                 ...
995   5098 days 19:04:54.224495
996   4419 days 20:40:54.224495
997   4884 days 20:17:54.224495
998   5000 days 20:20:54.224495
999   4272 days 20:29:54.224495
Name: date, Length: 1000, dtype: timedelta64[ns]

In [51]:
# in second

(today - time['date'])/ np.timedelta64(1,'s')

0      3.853263e+08
1      3.735801e+08
2      4.155680e+08
3      3.552602e+08
4      3.895658e+08
           ...
995    4.405359e+08
996    3.818761e+08
997    4.220507e+08
998    4.320733e+08
999    3.691746e+08
Name: date, Length: 1000, dtype: float64

In [52]:
# in minutes

(today - time['date'])/ np.timedelta64(1,'m')

0      6.422105e+06
1      6.226335e+06
2      6.926134e+06
3      5.921004e+06
4      6.492764e+06
           ...
995    7.342265e+06
996    6.364601e+06
997    7.034178e+06
998    7.201221e+06
999    6.152910e+06
Name: date, Length: 1000, dtype: float64

In [57]:
# in hours

(today - time['date'])/ np.timedelta64(1,'h')

0      107035.081729
1      103772.248396
2      115435.565062
3       98683.398396
4      108212.731729
           ...
995    122371.081729
996    106076.681729
997    117236.298396
998    120020.348396
999    102548.498396
Name: date, Length: 1000, dtype: float64